In [2]:
import pandas as pd

df = pd.read_csv(r'G:\Work\Chetu W4.53 FastAPI for ML Models\DeliveryAPISeg\PostDeliveryIndex\dataset\Delivery_Time_new.csv')
print(df.shape)

(10000, 17)

In [74]:
df.dropna()
df.head()

,Traffic_Level,ID,Delivery_person_ID,weather_description,Type_of_order,Type_of_vehicle,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,temperature,humidity,precipitation,Distance (km),TARGET
0,High,70A2,CHENRES12DEL01,mist,Snack,scooter,32,4.6,12.972.793,80.249.982,13.012.793,80.289.982,26.55,87.0,0.0,9.89,43.45
1,High,95B4,RANCHIRES15DEL01,clear sky,Meal,scooter,33,4.7,23.369.746,8.533.982,23.479.746,8.544.982,17.51,69.0,0.0,19.11,3.816.666.667
2,High,CDCD,DEHRES17DEL01,clear sky,Snack,motorcycle,36,4.2,30.327.968,78.046.106,30.397.968,78.116.106,12.44,77.0,0.0,11.59,3.636.666.667
3,High,2784,PUNERES13DEL03,clear sky,Drinks,scooter,23,4.7,1.856.245,73.916.619,1.865.245,74.006.619,19.37,65.0,0.0,21.93,49.45
4,High,6F67,HYDRES14DEL01,overcast clouds,Snack,motorcycle,34,4.9,17.426.228,78.407.495,17.496.228,78.477.495,21.29,64.0,0.0,18.26,5.248.333.333

In [75]:
df.Type_of_order.unique()

array(['Snack', 'Meal', 'Drinks', 'Buffet'], dtype=object)

In [76]:
df.rename(columns={'Type_of_order': 'type_of_package',
                   'Restaurant_latitude': 'PO_latitude',
                   'Restaurant_longitude': 'PO_longitude'}, inplace=True)

df.head()

,Traffic_Level,ID,Delivery_person_ID,weather_description,type_of_package,Type_of_vehicle,Delivery_person_Age,Delivery_person_Ratings,PO_latitude,PO_longitude,Delivery_location_latitude,Delivery_location_longitude,temperature,humidity,precipitation,Distance (km),TARGET
0,High,70A2,CHENRES12DEL01,mist,Snack,scooter,32,4.6,12.972.793,80.249.982,13.012.793,80.289.982,26.55,87.0,0.0,9.89,43.45
1,High,95B4,RANCHIRES15DEL01,clear sky,Meal,scooter,33,4.7,23.369.746,8.533.982,23.479.746,8.544.982,17.51,69.0,0.0,19.11,3.816.666.667
2,High,CDCD,DEHRES17DEL01,clear sky,Snack,motorcycle,36,4.2,30.327.968,78.046.106,30.397.968,78.116.106,12.44,77.0,0.0,11.59,3.636.666.667
3,High,2784,PUNERES13DEL03,clear sky,Drinks,scooter,23,4.7,1.856.245,73.916.619,1.865.245,74.006.619,19.37,65.0,0.0,21.93,49.45
4,High,6F67,HYDRES14DEL01,overcast clouds,Snack,motorcycle,34,4.9,17.426.228,78.407.495,17.496.228,78.477.495,21.29,64.0,0.0,18.26,5.248.333.333

In [3]:
df['type_of_package'].replace(['Snack', 'Meal', 'Drinks', 'Buffet'], ['Letter', 'Parcel', 'Package', 'Label'], inplace=True)
df.head()

C:\Users\Dhruv Sharma\AppData\Local\Temp\ipykernel_2856\2720769604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['type_of_package'].replace(['Snack', 'Meal', 'Drinks', 'Buffet'], ['Letter', 'Parcel', 'Package', 'Label'], inplace=True)

,Traffic_Level,ID,Delivery_person_ID,weather_description,type_of_package,Type_of_vehicle,Delivery_person_Age,Delivery_person_Ratings,PO_latitude,PO_longitude,Delivery_location_latitude,Delivery_location_longitude,temperature,humidity,precipitation,Distance (km),TARGET
0,High,70A2,CHENRES12DEL01,mist,Letter,scooter,32,4.6,12.972.793,80.249.982,13.012.793,80.289.982,26.55,87.0,0.0,9.89,43.45
1,High,95B4,RANCHIRES15DEL01,clear sky,Parcel,scooter,33,4.7,23.369.746,8.533.982,23.479.746,8.544.982,17.51,69.0,0.0,19.11,3.816.666.667
2,High,CDCD,DEHRES17DEL01,clear sky,Letter,motorcycle,36,4.2,30.327.968,78.046.106,30.397.968,78.116.106,12.44,77.0,0.0,11.59,3.636.666.667
3,High,2784,PUNERES13DEL03,clear sky,Package,scooter,23,4.7,1.856.245,73.916.619,1.865.245,74.006.619,19.37,65.0,0.0,21.93,49.45
4,High,6F67,HYDRES14DEL01,overcast clouds,Letter,motorcycle,34,4.9,17.426.228,78.407.495,17.496.228,78.477.495,21.29,64.0,0.0,18.26,5.248.333.333

In [4]:
df['weather_description'].unique()

array(['mist', 'clear sky', 'overcast clouds', 'broken clouds', 'haze',
       'scattered clouds', 'fog', 'smoke', 'few clouds', nan,
       'light rain', 'moderate rain'], dtype=object)

In [78]:
# df.to_csv('Delivery_Time_new_2.csv', index=False)

In [86]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import joblib

# --- Clean TARGET column ---
def clean_target(value):
    if isinstance(value, (int, float)):
        return value
    if isinstance(value, str):
        if value == '#VALUE!':
            return np.nan
        try:
            return float(value)
        except ValueError:
            # Handle values with multiple decimal points like '3.816.666.667'
            parts = value.split('.')
            if len(parts) > 1:
                return float(parts[0] + '.' + ''.join(parts[1:]))
            else:
                return float(value)
    return np.nan

df["TARGET"] = df["TARGET"].astype(str).apply(clean_target)

# Drop rows where TARGET could not be converted
df.dropna(subset=["TARGET"], inplace=True)

# --- Clean geolocation columns ---
cols_to_clean = ['PO_latitude', 'PO_longitude', 'Delivery_location_latitude', 'Delivery_location_longitude']
for col in cols_to_clean:
    df[col] = df[col].astype(str).str.replace('.', '', n=1, regex=False).astype(float)

# --- Encode categorical variables ---
categorical_cols = ["Traffic_Level", "weather_description", "type_of_package", "Type_of_vehicle"]
encoders = {}
for col in categorical_cols:
    enc = LabelEncoder()
    df[col] = enc.fit_transform(df[col].astype(str))
    encoders[col] = enc

# --- Split data ---
X = df.drop(["TARGET", "ID", "Delivery_person_ID"], axis=1)
y = df["TARGET"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# --- Train model ---
model = RandomForestRegressor()
model.fit(X_train, y_train)

# --- Save model and encoders ---
joblib.dump(model, "app/ml/delivery_time_predictor.pkl")
joblib.dump(encoders, "app/ml/encoders.pkl")

['encoders.pkl']

In [81]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import joblib
import numpy as np

# Handle non-numeric target values by replacing '#VALUE!' with NaN and converting to float
def clean_target(value):
    if isinstance(value, (int, float)):
        return value
    if isinstance(value, str):
        if value == '#VALUE!':
            return np.nan
        try:
            # Attempt to convert directly if it's already a valid float string
            return float(value)
        except ValueError:
            # Handle values with multiple decimal points
            parts = value.split('.')
            if len(parts) > 1:
                # Keep the first part and join the rest without decimals
                return float(parts[0] + '.' + ''.join(parts[1:]))
            else:
                # Should not happen if there are no decimals, but handle as float
                return float(value)
    return np.nan # Return NaN for any other unexpected types

df["TARGET"] = df["TARGET"].astype(str).apply(clean_target)

# Drop rows where TARGET is NaN after cleaning
df.dropna(subset=["TARGET"], inplace=True)


# Encode categorical variables
categorical_cols = ["Traffic_Level", "weather_description", "type_of_package", "Type_of_vehicle"]
encoders = {}
for col in categorical_cols:
    enc = LabelEncoder()
    # Ensure column is string type before encoding
    df[col] = enc.fit_transform(df[col].astype(str))
    encoders[col] = enc

# Ensure all features are numeric before splitting
# Drop non-numeric columns that are not part of the feature set X
numeric_df = df.select_dtypes(include=np.number)

X = numeric_df.drop(["TARGET"], axis=1)
y = df["TARGET"]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestRegressor()
model.fit(X_train, y_train)

joblib.dump(model, "delivery_time_predictor.pkl")
joblib.dump(encoders, "encoders.pkl")

['encoders.pkl']

In [55]:
cols_to_clean = ['PO_latitude', 'PO_longitude', 'Delivery_location_latitude', 'Delivery_location_longitude']
for col in cols_to_clean:
    # Convert to string, replace the second '.' with ''
    df[col] = df[col].astype(str).str.replace('.', '', n=1, regex=False).astype(float)
    # df[col] = df[col].astype(str).str.replace('.', '', regex=False, n=1).astype(float)

display(df.head())

,Traffic_Level,ID,Delivery_person_ID,weather_description,type_of_package,Type_of_vehicle,Delivery_person_Age,Delivery_person_Ratings,PO_latitude,PO_longitude,Delivery_location_latitude,Delivery_location_longitude,temperature,humidity,precipitation,Distance (km),TARGET
0,0,70A2,CHENRES12DEL01,6,1,3,32,4.6,129727930.0,802499820.0,130127930.0,802899820.0,26.55,87.0,0.0,9.89,43.45
1,0,95B4,RANCHIRES15DEL01,1,3,3,33,4.7,233697460.0,85339820.0,234797460.0,85449820.0,17.51,69.0,0.0,19.11,3.816.666.667
2,0,CDCD,DEHRES17DEL01,1,1,2,36,4.2,303279680.0,780461060.0,303979680.0,781161060.0,12.44,77.0,0.0,11.59,3.636.666.667
3,0,2784,PUNERES13DEL03,1,2,3,23,4.7,18562450.0,739166190.0,18652450.0,740066190.0,19.37,65.0,0.0,21.93,49.45
4,0,6F67,HYDRES14DEL01,9,1,2,34,4.9,174262280.0,784074950.0,174962280.0,784774950.0,21.29,64.0,0.0,18.26,5.248.333.333

In [56]:
# cols_to_clean = ['PO_latitude', 'PO_longitude', 'Delivery_location_latitude', 'Delivery_location_longitude']
# for col in cols_to_clean:
#     # Convert to string, replace the second '.' with ''
#     df[col] = df[col].astype(str).str.replace('.', '', n=1, regex=False).astype(float)

# display(df.head())

In [57]:
# cols_to_clean = ['PO_latitude', 'PO_longitude', 'Delivery_location_latitude', 'Delivery_location_longitude']
# for col in cols_to_clean:
#     df[col] = df[col].astype(str).str.replace('.', '', regex=False, n=1).astype(float)

# df.head()

In [58]:
# Drop rows with any null values
df.dropna(inplace=True)

# Verify that there are no more null values
print(df.isnull().sum())

Traffic_Level                  0
ID                             0
Delivery_person_ID             0
weather_description            0
type_of_package                0
Type_of_vehicle                0
Delivery_person_Age            0
Delivery_person_Ratings        0
PO_latitude                    0
PO_longitude                   0
Delivery_location_latitude     0
Delivery_location_longitude    0
temperature                    0
humidity                       0
precipitation                  0
Distance (km)                  0
TARGET                         0
dtype: int64

In [65]:
df.TARGET.unique()[:100]

array(['43.45', '3.816.666.667', '3.636.666.667', '49.45',
       '5.248.333.333', '3.461.666.667', '4.416.666.667', '5.438.333.333',
       '4.746.666.667', '4.728.333.333', '46.25', '4.061.666.667',
       '4.418.333.333', '46.45', '50.35', '4.971.666.667', '42.3',
       '4.548.333.333', '4.558.333.333', '4.021.666.667', '4.791.666.667',
       '48.2', '4.681.666.667', '5.281.666.667', '5.231.666.667', '33.3',
       '40.8', '4.573.333.333', '4.143.333.333', '4.601.666.667', '35.45',
       '4.428.333.333', '4.911.666.667', '4.663.333.333', '4.531.666.667',
       '33.15', '4.321.666.667', '5.013.333.333', '4.543.333.333',
       '3.933.333.333', '3.173.333.333', '37.75', '36.3', '4.481.666.667',
       '4.093.333.333', '3.488.333.333', '4.068.333.333', '32.2',
       '4.281.666.667', '5.158.333.333', '4.716.666.667', '34.9', '33.5',
       '4.413.333.333', '4.266.666.667', '4.323.333.333', '4.091.666.667',
       '47.9', '3.876.666.667', '41.1', '3.948.333.333', '41.55', '42.65',
       '4.898.333.333', '4.048.333.333', '4.836.666.667', '42.5', '37.45',
       '44.9', '5.243.333.333', '36.1', '4.388.333.333', '3.983.333.333',
       '56.25', '4.523.333.333', '4.286.666.667', '3.651.666.667',
       '4.878.333.333', '5.166.666.667', '4.006.666.667', '5.803.333.333',
       '4.816.666.667', '4.871.666.667', '38.15', '45.15',
       '4.318.333.333', '5.086.666.667', '5.546.666.667', '5.143.333.333',
       '53.6', '4.071.666.667', '4.151.666.667', '39.5', '5.788.333.333',
       '46.75', '35.05', '3.891.666.667', '4.283.333.333',
       '3.443.333.333', '54.8'], dtype=object)

In [63]:
search_value = '1.073.333.333'
found_in_columns = []

for col in df.columns:
    if (df[col] == search_value).any():
        found_in_columns.append(col)

if found_in_columns:
    print(f"The value '{search_value}' was found in the following columns: {found_in_columns}")
else:
    print(f"The value '{search_value}' was not found in any column.")

The value '1.073.333.333' was found in the following columns: ['TARGET']

In [ ]:
X = df.drop(["TARGET", "ID", "Delivery_person_ID"], axis=1)
y = df["TARGET"]
print(X.shape, y.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((7567, 14), (1892, 14), (7567,), (1892,))

In [60]:
X.head()

,Traffic_Level,weather_description,type_of_package,Type_of_vehicle,Delivery_person_Age,Delivery_person_Ratings,PO_latitude,PO_longitude,Delivery_location_latitude,Delivery_location_longitude,temperature,humidity,precipitation,Distance (km)
0,0,6,1,3,32,4.6,129727930.0,802499820.0,130127930.0,802899820.0,26.55,87.0,0.0,9.89
1,0,1,3,3,33,4.7,233697460.0,85339820.0,234797460.0,85449820.0,17.51,69.0,0.0,19.11
2,0,1,1,2,36,4.2,303279680.0,780461060.0,303979680.0,781161060.0,12.44,77.0,0.0,11.59
3,0,1,2,3,23,4.7,18562450.0,739166190.0,18652450.0,740066190.0,19.37,65.0,0.0,21.93
4,0,9,1,2,34,4.9,174262280.0,784074950.0,174962280.0,784774950.0,21.29,64.0,0.0,18.26

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9459 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Traffic_Level                9459 non-null   int64
 1   ID                           9459 non-null   object
 2   Delivery_person_ID           9459 non-null   object
 3   weather_description          9459 non-null   int64
 4   type_of_package              9459 non-null   int64
 5   Type_of_vehicle              9459 non-null   int64
 6   Delivery_person_Age          9459 non-null   int64
 7   Delivery_person_Ratings      9459 non-null   float64
 8   PO_latitude                  9459 non-null   float64
 9   PO_longitude                 9459 non-null   float64
 10  Delivery_location_latitude   9459 non-null   float64
 11  Delivery_location_longitude  9459 non-null   float64
 12  temperature                  9459 non-null   float64
 13  humidity                     9459 non-null   float64
 14  precipitation                9459 non-null   float64
 15  Distance (km)                9459 non-null   float64
 16  TARGET                       9459 non-null   object
dtypes: float64(9), int64(5), object(3)
memory usage: 1.3+ MB

In [62]:
model = RandomForestRegressor()
model.fit(X_train, y_train)

ValueError: could not convert string to float: '1.073.333.333'

In [ ]:
joblib.dump(model, "delivery_time_predictor.pkl")
joblib.dump(encoders, "encoders.pkl")